export const constant = {
  "BASE_URL": "https://newsapi.org/v2/",
  "API_KEY": "4e9a49c980d24649bc8549083b7dcc3a",
  "COUNTRIES": [{name: "", value: "ae"},
  {name: "", value: "ar"},
  {name: "", value: "at"},
  {name: "", value: "au"},
  {name: "", value: "be"},
  {name: "", value: "bg"},
  {name: "", value: "br"},
  {name: "", value: "ca"},
  {name: "", value: "ch"},
  {name: "", value: "cn"},
  {name: "", value: "co"},
  {name: "", value: "cu"},
  {name: "", value: "cz"},
  {name: "", value: "de"},
  {name: "", value: "eg"},
  {name: "", value: "fr"},
  {name: "", value: "gb"},
  {name: "", value: "gr"},
  {name: "", value: "hk"},
  {name: "", value: "hu"},
  {name: "", value: "id"},
  {name: "", value: "ie"},
  {name: "", value: "il"},
  {name: "", value: "in"},
  {name: "", value: "it"},
  {name: "", value: "jp"},
  {name: "", value: "kr"},
  {name: "", value: "lt"},
  {name: "", value: "lv"},
  {name: "", value: "ma"},
  {name: "", value: "mx"},
  {name: "", value: "my"},
  {name: "", value: "ng"},
  {name: "", value: "nl"},
  {name: "", value: "no"},
  {name: "", value: "nz"},
  {name: "", value: "ph"},
  {name: "", value: "pl"},
  {name: "", value: "pt"},
  {name: "", value: "ro"},
  {name: "", value: "rs"},
  {name: "", value: "ru"},
  {name: "", value: "sa"},
  {name: "", value: "se"},
  {name: "", value: "sg"},
  {name: "", value: "si"},
  {name: "", value: "sk"},
  {name: "", value: "th"},
  {name: "", value: "tr"},
  {name: "", value: "tw"},
  {name: "", value: "ua"},
  {name: "", value: "us"},
  {name: "", value: "ve"},
  {name: "", value: "za"}]
}